# Generated by Django 6.0.1 on 2026-01-12 04:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0002_alter_review_product'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Product',
            new_name='Project',
        ),
        migrations.RenameField(
            model_name='review',
            old_name='product',
            new_name='project',
        ),
    ]
